### ISSUE TITLE
load_all() fails when invoked from parallel "make"

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1070]
A strange one: If a `Makefile` contains a rule that invokes `load_all()` on a package, this will fail if `make` has been called with the `-j ...` switch (=parallelize). To replicate:

```bash
git clone https://github.com/krlmlr/r-appveyor.git -b parallel-load-all
cd r-appveyor
make -j4 install
```

Output:

```
git clean -fdx; Rscript --vanilla -e "devtools::load_all()"
Removing src/RcppExports.o
Loading fakepackage
Re-compiling fakepackage
'/usr/lib/R/bin/R' --vanilla CMD INSTALL '/home/muelleki/git/R/r-appveyor'  \
  --library='/tmp/Rtmpr5cRjK' --no-R --no-data --no-help --no-demo --no-inst  \
  --no-docs --no-exec --no-multiarch --no-test-load 

* installing *source* package ‘fakepackage’ ...
** libs
make[1]: Entering directory '/home/muelleki/git/R/r-appveyor/src'
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/muelleki/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -UNDEBUG -Wall -pedantic -g -O0 -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
make[1]: *** read jobs pipe: No such file or directory.  Stop.
make[1]: *** Waiting for unfinished jobs....

make[1]: Leaving directory '/home/muelleki/git/R/r-appveyor/src'
ERROR: compilation failed for package ‘fakepackage’
* removing ‘/tmp/Rtmpr5cRjK/fakepackage’
Error: Command failed (1)
Execution halted
Makefile:4: recipe for target 'install' failed
make: *** [install] Error 1
```

Tested on Ubuntu 15.10. This issue was present even in devtools 1.6. On the other hand, `make install` succeeds.

**Comment by jimhester** [comment]
What version of make do you have. Your test works on my machine OS X 10.11.2 (with an admittedly old version of make)
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
`

**Comment by krlmlr** [comment]
Thanks for looking into it.

```
$ make -v
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

It's strange that I didn't have any problems a few months ago, also with make 4.0. Please feel free to close -- I've worked around it, and it may be just too minor.

**Comment by jimhester** [comment]
And sure enough if I use a newer version of make I can reproduce this
```
> make -v
GNU Make 4.1
Built for x86_64-apple-darwin15.2.0
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

>make -j4 install
git clean -fdx; Rscript --vanilla -e "devtools::load_all()"
Removing src/RcppExports.o
Removing src/fakepackage.so
Removing src/hello.o
Loading fakepackage
Re-compiling fakepackage
'/usr/local/Cellar/r/3.2.3/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore CMD INSTALL  \
  '/Users/jhester/pkg/r-appveyor'  \
  --library='/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T//RtmpI49ilp/devtools_install_2497d1c95e9'  \
  --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec  \
  --no-multiarch --no-test-load

* installing *source* package ‘fakepackage’ ...
** libs
clang++ -I/usr/local/Cellar/r/3.2.3/R.framework/Resources/include -DNDEBUG -I/usr/local/include  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/usr/local/include -I"/usr/local/lib/R/3.2/site-library/Rcpp/include" -I/usr/local/include   -fPIC  -g -O2  -c RcppExports.cpp -o RcppExports.o
make[1]: *** read jobs pipe: No such file or directory.  Stop.
make[1]: *** Waiting for unfinished jobs....
ERROR: compilation failed for package ‘fakepackage’
* removing ‘/private/var/folders/dt/r5s12t392tb5sk181j3gs4zw0000gn/T/RtmpI49ilp/devtools_install_2497d1c95e9/fakepackage’
Error: Command failed (1)
Execution halted
Makefile:4: recipe for target 'install' failed
gmake: *** [install] Error 1
```
I don't really know the solution though, it looks to me like the downstream make calls are inheriting the parameters of the top level make and the downstream makefile does not support parallel make.

**Comment by krlmlr** [comment]
I forgot to say: If you use `R CMD INSTALL $*` as recipe in the Makefile, it works again (branch "parallel-install" in the test repo). This makes me think that it's something that devtools does that triggers this behavior.
