### ISSUE TITLE
RTools 3.2 is compatible with R 3.1.2

### ISSUE THREAD

**Issue by juancentro** [hadley/devtools#717]
I recently installed RTools 3.2 (over an RTools 3.1 installation, without executing the RTools installer first).
When using `install_github` I get this

```
> devtools::install_github("hadley/lineprof")
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.1.2 was found. Rtools 3.1 was previously installed in c:/Rtools but now that directory contains Rtools 3.2.

Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/ and then run find_rtools().
Downloading github repo hadley/lineprof@master
Installing lineprof
"C:/R/R-31~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/B03964/AppData/Local/Temp/RtmpCUSCDc/devtools1fa053cf66f5/hadley-lineprof-a966473"  \
  --library="C:/R/R-3.1.2/library" --install-tests 

Loading required package: bitops
* installing *source* package 'lineprof' ...
** libs

*** arch - i386
g++ -m32 -I"C:/R/R-31~1.2/include" -DNDEBUG    -I"C:/R/R-3.1.2/library/Rcpp/include" -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
g++: not found
make: *** [RcppExports.o] Error 127
Aviso: comando ejecutado 'make -f "C:/R/R-31~1.2/etc/i386/Makeconf" -f "C:/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="lineprof.dll" OBJECTS="RcppExports.o contains.o parse-refs.o pause.o"' tiene estatus 2
ERROR: compilation failed for package 'lineprof'
* removing 'C:/R/R-3.1.2/library/lineprof'
Error: Command failed (1)
```

but per http://cran.r-project.org/bin/windows/Rtools/ RTools 3.2 is compatible with R 3.1.2

**Comment by juancentro** [comment]
It seems that the variable `version_info` doesn't hold information for my 3.2 installation. I reverted to RTools 3.1 temporarily

**Comment by dtenenba** [comment]
I also get this when using R-devel (R-3.2.0), which should definitely be compatible with Rtools-3.2.

**Comment by jakesherman** [comment]
I am having the same issue.

**Comment by dtenenba** [comment]
Just to add, there is now an Rtools version 33 (which works with R-devel/3.2.0) so devtools needs to recognize that as well as a valid version. The warning that's produced is confusing a lot of people into thinking they have done something wrong.

**Comment by jimhester** [comment]
This should be fixed in devtools develpment version on github

[R/rtools.r#L252-L255](https://github.com/hadley/devtools/blame/f15407096a5d42f6780c632f5f6d8500a2f122c3/R/rtools.r#L252-L255)

But is _not_ fixed in the last released devtools on CRAN, so if you are getting this error for now the solution should be to use the development version.

**Comment by dtenenba** [comment]
If I read this right, it will still give an error under Rtools 3.3.

**Comment by jimhester** [comment]
Ah right, you are correct now that they have rolled back to using `gcc 4.6.3` this needs to be updated with

```r
  "3.3" = list(
    version_min = "3.2.0",
    version_max = "3.2.99",
    path = c("bin", "gcc-4.6.3/bin")
  )
```
Which I think should fix things using Rtools33.

**Comment by juancentro** [comment]
I still get
```
WARNING: Rtools 3.3 found on the path at c:/Rtools is not compatible with R 3.2.0.

Please download and install Rtools 3.1 from http://cran.r-project.org/bin/windows/Rtools/, remove the incompatible version from your PATH, then run find_rtools().
```
when using R 3.2.0 with RTools 3.3

**Comment by hadley** [comment]
Duplicate of #738

**Comment by dtenenba** [comment]
Doesn't seem like a duplicate to me.

**Comment by ropeladder** [comment]
I'm getting the exact same error as juancentro.

**Comment by juancentro** [comment]
This is fixed in the latest commit on the master branch

**Comment by Kapondo** [comment]
I recently installed RTools 3.4 (over an RTools 3.3 installation, after having problem with building R Package). There seems to be incompatibility issues between RTools 3.4 and R version 3.3.0 (2016-05-03). I reverted back to RTools 3.3 but when I try to build and reload a trial package I get the following error message:

==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating topten documentation
Loading topten
Writing topten.Rd
Writing predct10.Rd
Writing NAMESPACE
Documentation completed

==> Rcmd.exe INSTALL --no-multiarch --with-keep.source topten

* installing to library 'C:/Program Files/R/R-3.3.0/library'
* installing *source* package 'topten' ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (topten)
WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:

  - Rtools 3.3 (installed at c:\Rtools)

Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/

when I run devtools::find_rtools() with RTools 3.3 installed I get TRUE

but with RTools 3.4 installed and run devtools::find_rtools() I get the below error message:

WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.3.0 was found. Rtools 3.3 was previously installed in c:/Rtools but now that directory contains Rtools 3.4.

Please download and install Rtools 3.3 from http://cran.r-project.org/bin/windows/Rtools/.

Please help!!

**Comment by hadley** [comment]
@Kapondo please file a new issue - a comment on a closed issue is likely to get missed.
